### ISSUE TITLE
You can run with 2 backpacks

### ISSUE THREAD

**Issue by Timassik** [mjc4wilton/BackpackOnChestRedux#11]
**Arma 3 Version:** `Game version:  2.14.150957` (stable)
**CBA Version:** last
**ACE3 Version:** last

**Mods:**
- CBA_A3
- ace

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- 
Put on 2 backpacks. And spam with the Z + X buttons (buttons for lying down and getting up) so that the animation of falling to the ground is interrupted. So the player can sprint.
The main thing is not to let it fall to the ground.

**Where did the issue occur?**
-all

**Comment by rautamiekka** [comment]
Please stop using `last`/`latest` as a version number, it harms more than it helps.

**Comment by mjc4wilton** [comment]
This is not an issue with Backpack on Chest. This is an issue with vanilla Arma 3's `forceWalk` command and you should report it on the bohemia interactive bug tracker (https://feedback.bistudio.com/project/view/1/)
